name: Unit Tests - Bicep Files and Modules

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.bicep"
      - "ps-rule.yaml"
      - ".ps-rule/*"
      - "**/bicepconfig.json"
  workflow_dispatch: {}

jobs:
  bicep_unit_tests:
    name: Bicep Build & Lint All Modules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List Currently Installed Bicep Version
        shell: pwsh
        run: |
          $bicepVersion = bicep --version
          Write-Information "=====> Currently installed Bicep version is: $bicepVersion <=====" -InformationAction Continue

      - name: Install latest version of Bicep
        shell: sh
        run: |
          # From https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/install#linux
          # Fetch the latest Bicep CLI binary
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          # Mark it as executable
          chmod +x ./bicep
          # Add bicep to your PATH (requires admin)
          sudo mv ./bicep /usr/local/bin/bicep
          # Verify you can now access the 'bicep' command
          bicep --help
          # Done!

      - name: List Now Installed Bicep Version
        shell: pwsh
        run: |
          $bicepVersion = bicep --version
          Write-Information "=====> Now installed Bicep version is: $bicepVersion <=====" -InformationAction Continue

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Validate templates
        shell: pwsh
        run: |
          Get-ChildItem -Recurse -Filter '*.bicep' -Exclude '.\omfra-as-code\bicep\CRML\*','callModuleFromACR.example.bicep','orchHubSpoke.bicep', '' | ForEach-Object {
            Write-Information "==> Attempting Bicep Deploy For File: $_" -InformationAction Continue
            $bicepTemplate = $_.FullName
            $parametersDirectory = "$_.DirectoryName\parameters"
            Get-ChildItem -Path $parametersDirectory -Recurse -Filter '*.bicepparam' -Exclude *.sample.*.bicepparam | ForEach-Object {
              Write-Information "==> Attempting Bicep Deploy For File: $bicepTemplate | Paramters: $_" -InformationAction Continue
              $bicepParameters = $_.FullName
              $bicepOutput = az deployment sub validate --template-file $bicepTemplate --parameters @$bicepParameters 2>&1
              if ($LastExitCode -ne 0)
              {
                foreach ($item in $bicepOutput) {
                  $output += "$($item) `r`n"
                }
              }
              Else
              {
                echo "Bicep Build Successful for File: $bicepTemplate"
              }
            }
          }

  azure_waf:
    name: Test Azure Well-Architected Framework (PSRule)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Add pipeline tests for Azure Well-Architected Framework.
      # See https://aka.ms/ps-rule-action for configuration options.
      - name: Run PSRule analysis
        uses: Microsoft/ps-rule@v2
        with:
          modules: PSRule.Rules.Azure
          baseline: Azure.Preview
        continue-on-error: true
