name: Deploy - Deploy infrastructure with Bicep and Modules

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy.yml"
      - ".github/scripts/*"
      - "**.bicep"
      - "**.bicepparam"
      - "ps-rule.yaml"
      - ".ps-rule/*"
      - "**/bicepconfig.json"
    paths-ignore:
      - "*.sample.*.bicepparam"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List Currently Installed Bicep Version
        shell: pwsh
        run: |
          $bicepVersion = bicep --version
          Write-Information "=====> Currently installed Bicep version is: $bicepVersion <=====" -InformationAction Continue

      - name: Install latest version of Bicep
        shell: sh
        run: |
          # From https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/install#linux
          # Fetch the latest Bicep CLI binary
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
      
      - name: List Now Installed Bicep Version
        shell: pwsh
        run: |
          $bicepVersion = bicep --version
          Write-Information "=====> Now installed Bicep version is: $bicepVersion <=====" -InformationAction Continue

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Validate templates
        shell: pwsh
        run: |
          ./.github/scripts/validate-bicep.ps1

      - name: Deploy all Bicep templates
        shell: pwsh
        run: |
          ./.github/scripts/deploy-bicep.ps1
